repos:
  - repo: local
    hooks:
      - id: pio-check
        name: PlatformIO Static Analysis
        entry: bash
        args:
          - -c
          - pio check --fail-on-defect=low --fail-on-defect=medium --fail-on-defect=high
        language: system
        types: [c, c++]
      - id: pio-test
        name: PlatformIO Test
        entry: bash
        args:
          - -c
          - pio test
        language: system
        types: [c, c++]
